# Generated by Django 5.2.7 on 2025-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiocontent",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]
