# Generated by Django 5.2.7 on 2025-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_audiocontent_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiocontent",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
