# Generated by Django 5.2.7 on 2025-10-31 05:00

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontent",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.storage_backends.SupabasePrivateStorage(),
                upload_to="audios/",
            ),
        ),
    ]
