# Generated by Django 5.2.7 on 2025-11-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_audiocontent_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontent",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]
