# Generated by Django 5.2.7 on 2025-11-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_audiocontent_audio_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiocontent",
            name="audio_data",
        ),
    ]
