# Generated by Django 5.2.7 on 2025-11-03 02:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_audiocontent_audio_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiocontent",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.get_audio_storage,
                upload_to=core.models.audio_upload_path,
            ),
        ),
    ]
